//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoServicios.ProxyUbigeo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="dataUbigeo", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hotel")]
    [System.SerializableAttribute()]
    public partial class dataUbigeo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdContinenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdPaisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbiCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbiContinenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbiPaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCiudad {
            get {
                return this.IdCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.IdCiudadField, value) != true)) {
                    this.IdCiudadField = value;
                    this.RaisePropertyChanged("IdCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdContinente {
            get {
                return this.IdContinenteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdContinenteField, value) != true)) {
                    this.IdContinenteField = value;
                    this.RaisePropertyChanged("IdContinente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdPais {
            get {
                return this.IdPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.IdPaisField, value) != true)) {
                    this.IdPaisField = value;
                    this.RaisePropertyChanged("IdPais");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo {
            get {
                return this.IdUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUbigeoField, value) != true)) {
                    this.IdUbigeoField = value;
                    this.RaisePropertyChanged("IdUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbiCiudad {
            get {
                return this.UbiCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.UbiCiudadField, value) != true)) {
                    this.UbiCiudadField = value;
                    this.RaisePropertyChanged("UbiCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbiContinente {
            get {
                return this.UbiContinenteField;
            }
            set {
                if ((object.ReferenceEquals(this.UbiContinenteField, value) != true)) {
                    this.UbiContinenteField = value;
                    this.RaisePropertyChanged("UbiContinente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UbiPais {
            get {
                return this.UbiPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.UbiPaisField, value) != true)) {
                    this.UbiPaisField = value;
                    this.RaisePropertyChanged("UbiPais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUbigeo.IServicioUbigeo")]
    public interface IServicioUbigeo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetAllContinentes", ReplyAction="http://tempuri.org/IServicioUbigeo/GetAllContinentesResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo> GetAllContinentes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetAllContinentes", ReplyAction="http://tempuri.org/IServicioUbigeo/GetAllContinentesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo>> GetAllContinentesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetAllPaises", ReplyAction="http://tempuri.org/IServicioUbigeo/GetAllPaisesResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo> GetAllPaises(string codContinente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetAllPaises", ReplyAction="http://tempuri.org/IServicioUbigeo/GetAllPaisesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo>> GetAllPaisesAsync(string codContinente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetAllCiudades", ReplyAction="http://tempuri.org/IServicioUbigeo/GetAllCiudadesResponse")]
        System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo> GetAllCiudades(string codContinente, string codPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetAllCiudades", ReplyAction="http://tempuri.org/IServicioUbigeo/GetAllCiudadesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo>> GetAllCiudadesAsync(string codContinente, string codPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetIdUbigeo", ReplyAction="http://tempuri.org/IServicioUbigeo/GetIdUbigeoResponse")]
        string GetIdUbigeo(string codContinente, string codPais, string codCiudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetIdUbigeo", ReplyAction="http://tempuri.org/IServicioUbigeo/GetIdUbigeoResponse")]
        System.Threading.Tasks.Task<string> GetIdUbigeoAsync(string codContinente, string codPais, string codCiudad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioUbigeoChannel : CapaAccesoServicios.ProxyUbigeo.IServicioUbigeo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioUbigeoClient : System.ServiceModel.ClientBase<CapaAccesoServicios.ProxyUbigeo.IServicioUbigeo>, CapaAccesoServicios.ProxyUbigeo.IServicioUbigeo {
        
        public ServicioUbigeoClient() {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo> GetAllContinentes() {
            return base.Channel.GetAllContinentes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo>> GetAllContinentesAsync() {
            return base.Channel.GetAllContinentesAsync();
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo> GetAllPaises(string codContinente) {
            return base.Channel.GetAllPaises(codContinente);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo>> GetAllPaisesAsync(string codContinente) {
            return base.Channel.GetAllPaisesAsync(codContinente);
        }
        
        public System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo> GetAllCiudades(string codContinente, string codPais) {
            return base.Channel.GetAllCiudades(codContinente, codPais);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<CapaAccesoServicios.ProxyUbigeo.dataUbigeo>> GetAllCiudadesAsync(string codContinente, string codPais) {
            return base.Channel.GetAllCiudadesAsync(codContinente, codPais);
        }
        
        public string GetIdUbigeo(string codContinente, string codPais, string codCiudad) {
            return base.Channel.GetIdUbigeo(codContinente, codPais, codCiudad);
        }
        
        public System.Threading.Tasks.Task<string> GetIdUbigeoAsync(string codContinente, string codPais, string codCiudad) {
            return base.Channel.GetIdUbigeoAsync(codContinente, codPais, codCiudad);
        }
    }
}
