//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_PeruHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HABITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HABITACION()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public string id_habitacion { get; set; }
        public string habi_num { get; set; }
        public string habi_piso { get; set; }
        public string habi_estado { get; set; }
        public string id_tipo_habi { get; set; }
        public string id_hotel { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
        public virtual TIPO_HABITACION TIPO_HABITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
