//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_PeruHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RESERVA()
        {
            this.HABITACION = new HashSet<HABITACION>();
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public string id_reserva { get; set; }
        public string id_cliente { get; set; }
        public string id_promocion { get; set; }
        public System.DateTime reser_fechaReser { get; set; }
        public System.DateTime reser_fechaIngreso { get; set; }
        public Nullable<System.DateTime> reser_fechaSalida { get; set; }
        public string reser_estado { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PROMOCION PROMOCION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HABITACION> HABITACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
