//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_PeruHotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaDetalleServicio
    {
        public string id_cliente { get; set; }
        public string id_reserva { get; set; }
        public string id_servicio { get; set; }
        public string servi_descripcion { get; set; }
        public Nullable<decimal> servi_precio { get; set; }
        public string cantidad { get; set; }
    }
}
