//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaAccesoServicios.ProxyCliente {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataCliente", Namespace="http://schemas.datacontract.org/2004/07/WCF_Hotel")]
    [System.SerializableAttribute()]
    public partial class DataCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieApeMaterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieApePaterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieContraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieCorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieDniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieNomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieSexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClieTelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomContinenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomPaisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieApeMater {
            get {
                return this.ClieApeMaterField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieApeMaterField, value) != true)) {
                    this.ClieApeMaterField = value;
                    this.RaisePropertyChanged("ClieApeMater");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieApePater {
            get {
                return this.ClieApePaterField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieApePaterField, value) != true)) {
                    this.ClieApePaterField = value;
                    this.RaisePropertyChanged("ClieApePater");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieCodigo {
            get {
                return this.ClieCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieCodigoField, value) != true)) {
                    this.ClieCodigoField = value;
                    this.RaisePropertyChanged("ClieCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieContra {
            get {
                return this.ClieContraField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieContraField, value) != true)) {
                    this.ClieContraField = value;
                    this.RaisePropertyChanged("ClieContra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieCorreo {
            get {
                return this.ClieCorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieCorreoField, value) != true)) {
                    this.ClieCorreoField = value;
                    this.RaisePropertyChanged("ClieCorreo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieDni {
            get {
                return this.ClieDniField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieDniField, value) != true)) {
                    this.ClieDniField = value;
                    this.RaisePropertyChanged("ClieDni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieEstado {
            get {
                return this.ClieEstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieEstadoField, value) != true)) {
                    this.ClieEstadoField = value;
                    this.RaisePropertyChanged("ClieEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieNom {
            get {
                return this.ClieNomField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieNomField, value) != true)) {
                    this.ClieNomField = value;
                    this.RaisePropertyChanged("ClieNom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieSexo {
            get {
                return this.ClieSexoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieSexoField, value) != true)) {
                    this.ClieSexoField = value;
                    this.RaisePropertyChanged("ClieSexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClieTelefono {
            get {
                return this.ClieTelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClieTelefonoField, value) != true)) {
                    this.ClieTelefonoField = value;
                    this.RaisePropertyChanged("ClieTelefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente {
            get {
                return this.IdClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.IdClienteField, value) != true)) {
                    this.IdClienteField = value;
                    this.RaisePropertyChanged("IdCliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUbigeo {
            get {
                return this.IdUbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUbigeoField, value) != true)) {
                    this.IdUbigeoField = value;
                    this.RaisePropertyChanged("IdUbigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCiudad {
            get {
                return this.NomCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.NomCiudadField, value) != true)) {
                    this.NomCiudadField = value;
                    this.RaisePropertyChanged("NomCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomContinente {
            get {
                return this.NomContinenteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomContinenteField, value) != true)) {
                    this.NomContinenteField = value;
                    this.RaisePropertyChanged("NomContinente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPais {
            get {
                return this.NomPaisField;
            }
            set {
                if ((object.ReferenceEquals(this.NomPaisField, value) != true)) {
                    this.NomPaisField = value;
                    this.RaisePropertyChanged("NomPais");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCliente.IServicioCliente")]
    public interface IServicioCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/GetCliente", ReplyAction="http://tempuri.org/IServicioCliente/GetClienteResponse")]
        CapaAccesoServicios.ProxyCliente.DataCliente GetCliente(string strDni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/GetCliente", ReplyAction="http://tempuri.org/IServicioCliente/GetClienteResponse")]
        System.Threading.Tasks.Task<CapaAccesoServicios.ProxyCliente.DataCliente> GetClienteAsync(string strDni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/RegistrarCliente", ReplyAction="http://tempuri.org/IServicioCliente/RegistrarClienteResponse")]
        bool RegistrarCliente(CapaAccesoServicios.ProxyCliente.DataCliente objCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCliente/RegistrarCliente", ReplyAction="http://tempuri.org/IServicioCliente/RegistrarClienteResponse")]
        System.Threading.Tasks.Task<bool> RegistrarClienteAsync(CapaAccesoServicios.ProxyCliente.DataCliente objCliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioClienteChannel : CapaAccesoServicios.ProxyCliente.IServicioCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClienteClient : System.ServiceModel.ClientBase<CapaAccesoServicios.ProxyCliente.IServicioCliente>, CapaAccesoServicios.ProxyCliente.IServicioCliente {
        
        public ServicioClienteClient() {
        }
        
        public ServicioClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CapaAccesoServicios.ProxyCliente.DataCliente GetCliente(string strDni) {
            return base.Channel.GetCliente(strDni);
        }
        
        public System.Threading.Tasks.Task<CapaAccesoServicios.ProxyCliente.DataCliente> GetClienteAsync(string strDni) {
            return base.Channel.GetClienteAsync(strDni);
        }
        
        public bool RegistrarCliente(CapaAccesoServicios.ProxyCliente.DataCliente objCliente) {
            return base.Channel.RegistrarCliente(objCliente);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarClienteAsync(CapaAccesoServicios.ProxyCliente.DataCliente objCliente) {
            return base.Channel.RegistrarClienteAsync(objCliente);
        }
    }
}
