//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SERVICIO
    {
        public string id_servicio { get; set; }
        public string id_reserva { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
