//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_HABITACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_HABITACION()
        {
            this.HABITACION = new HashSet<HABITACION>();
        }
    
        public string id_tipo_habi { get; set; }
        public string tipo_nombre { get; set; }
        public string tipo_descripcion { get; set; }
        public decimal tipo_precio { get; set; }
        public string tipo_num_camas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HABITACION> HABITACION { get; set; }
    }
}
