//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaReservaServicios
    {
        public string id_reserva { get; set; }
        public string id_cliente { get; set; }
        public Nullable<int> Cantidad_ser { get; set; }
        public Nullable<decimal> Monto_servicio { get; set; }
    }
}
